"use client";
import { useMemo, useState, useEffect } from "react";

type Priority = "low" | "medium" | "high";
type Task = { id: string; title: string; category: string; dueDate: string; priority: Priority; completed: boolean };
type Goal = { id: string; title: string; description: string; category: string; targetDate: string; progress: number; status: string; milestones: { text: string; done: boolean }[] };
type Meal = { id: string; name: string; calories: number; protein: number; carbs: number; fat: number };
type Note = { id: string; title: string; body: string; tags: string; pinned: boolean };
type Entry = { id: string; type: "income"|"expense"|"savings"|"debt"; amount: number; category: string };
type Review = { id: string; done: string; slowed: string; learned: string; focus: string; rating: number };
type Skill = { name: string; xp: number };

const seed = { tasks:[{id:"1",title:"Study cybersecurity for 45 minutes",category:"Cybersecurity",dueDate:new Date().toISOString().slice(0,10),priority:"high",completed:false}], goals:[{id:"g1",title:"Build Life OS MVP",description:"Finish core modules",category:"Personal",targetDate:"2026-06-20",progress:50,status:"In progress",milestones:[{text:"Dashboard",done:true},{text:"Tasks+XP",done:false}]}], meals:[], notes:[{id:"n1",title:"Sales pitch idea",body:"Lead with pain point.",tags:"Sales scripts",pinned:true}], entries:[{id:"e1",type:"income",amount:4200,category:"Salary"}], reviews:[], skills:["Cybersecurity","Cloud","SQL","AI Governance","Sales","Productivity","Fitness","Money"].map((name,i)=>({name,xp:80+i*20})), settings:{name:"Alex",calories:2400,protein:180,carbs:220,fat:70,savingsGoal:1000,favoriteSkills:"Cybersecurity,Sales",theme:"dark",xpAnimations:true}, xp:120, streak:4 };

const key = "life-os-v1";
const lvl = (xp:number)=>Math.floor(Math.sqrt(xp/100))+1;
const xpToNext=(xp:number)=>lvl(xp)*100;
const uid=()=>Math.random().toString(36).slice(2,9);

export default function Home() {
  const [tab,setTab]=useState("Dashboard");
  const [state,setState]=useState<any>(seed);
  useEffect(()=>{const s=localStorage.getItem(key); if(s) setState(JSON.parse(s));},[]);
  useEffect(()=>{localStorage.setItem(key,JSON.stringify(state));},[state]);
  const totals=useMemo(()=>{const consumed=state.meals.reduce((a:any,m:Meal)=>({cal:a.cal+m.calories,p:a.p+m.protein,c:a.c+m.carbs,f:a.f+m.fat}),{cal:0,p:0,c:0,f:0}); const spent=state.entries.filter((e:Entry)=>e.type==="expense").reduce((a:number,e:Entry)=>a+e.amount,0); const saved=state.entries.filter((e:Entry)=>e.type==="savings").reduce((a:number,e:Entry)=>a+e.amount,0); return {consumed,spent,saved};},[state]);
  const grantXp=(v:number)=>setState((s:any)=>({...s,xp:s.xp+v}));

  const nav=["Dashboard","Tasks","Goals","Study","Fitness","Money","Notes","Review","Settings"];
  return <main className="min-h-screen p-4 md:p-6"><div className="grid gap-4 md:grid-cols-[220px_1fr_320px]"><aside className="card h-fit"><h1 className="text-2xl font-bold mb-4">Life OS</h1>{nav.map(n=><button key={n} onClick={()=>setTab(n)} className={`btn w-full text-left mb-2 ${tab===n?"bg-indigo-600 hover:bg-indigo-500":""}`}>{n}</button>)}</aside><section className="space-y-4">{tab==="Dashboard"&&<div className="space-y-4"><div className="card"><h2 className="text-xl font-semibold">Hey {state.settings.name}, {new Date().toDateString()}</h2><p className="text-slate-300">Daily focus: Execute top priorities and protect momentum.</p><div className="mt-3 h-3 rounded-full bg-slate-800"><div className="h-3 rounded-full bg-indigo-500" style={{width:`${Math.min((state.xp/xpToNext(state.xp))*100,100)}%`}}/></div><p className="text-sm mt-2">Level {lvl(state.xp)} • {state.xp} XP • next at {xpToNext(state.xp)}</p></div><div className="grid md:grid-cols-3 gap-3">{[["Tasks done",state.tasks.filter((t:Task)=>t.completed).length],["Study minutes",state.skills.reduce((a:number,s:Skill)=>a+s.xp,0)],["Calories left",state.settings.calories-totals.consumed.cal],["Saved month",`$${totals.saved}`],["Streak",state.streak]].map(([k,v])=><div key={String(k)} className="card"><p className="text-slate-400 text-sm">{k}</p><p className="text-2xl font-semibold">{v}</p></div>)}</div></div>}
{tab==="Tasks"&&<Tasks state={state} setState={setState} grantXp={grantXp}/>}
{tab==="Goals"&&<Goals state={state} setState={setState} grantXp={grantXp}/>}
{tab==="Study"&&<Study state={state} setState={setState} grantXp={grantXp}/>}
{tab==="Fitness"&&<Fitness state={state} setState={setState} totals={totals}/>}
{tab==="Money"&&<Money state={state} setState={setState} totals={totals}/>}
{tab==="Notes"&&<Notes state={state} setState={setState}/>}
{tab==="Review"&&<Review state={state} setState={setState} grantXp={grantXp}/>}
{tab==="Settings"&&<Settings state={state} setState={setState}/>}
</section><Assistant/></div></main>
}

function Tasks({state,setState,grantXp}:any){const [f,setF]=useState({title:"",category:"Work",dueDate:"",priority:"medium" as Priority}); return <div className="card"><h3 className="font-semibold mb-3">Tasks</h3><div className="grid md:grid-cols-4 gap-2 mb-3"><input className="input" placeholder="Task" value={f.title} onChange={e=>setF({...f,title:e.target.value})}/><input className="input" placeholder="Category" value={f.category} onChange={e=>setF({...f,category:e.target.value})}/><input className="input" type="date" value={f.dueDate} onChange={e=>setF({...f,dueDate:e.target.value})}/><select className="input" value={f.priority} onChange={e=>setF({...f,priority:e.target.value as Priority})}><option>low</option><option>medium</option><option>high</option></select></div><button className="btn" onClick={()=>f.title&&setState((s:any)=>({...s,tasks:[{id:uid(),completed:false,...f},...s.tasks]}))}>Add task</button><div className="mt-3 space-y-2">{state.tasks.map((t:Task)=><div key={t.id} className="rounded-xl bg-slate-800 p-3 flex justify-between"><div><p>{t.title}</p><p className="text-xs text-slate-400">{t.category} • {t.priority} • {t.dueDate}</p></div><div className="flex gap-2"><button className="btn" onClick={()=>{if(!t.completed) grantXp(t.priority==="high"?20:t.priority==="medium"?10:5); setState((s:any)=>({...s,tasks:s.tasks.map((x:Task)=>x.id===t.id?{...x,completed:!x.completed}:x)}));}}>{t.completed?"Undo":"Complete"}</button><button className="btn" onClick={()=>setState((s:any)=>({...s,tasks:s.tasks.filter((x:Task)=>x.id!==t.id)}))}>Delete</button></div></div>)}</div></div>}
function Goals({state,setState,grantXp}:any){const [title,setTitle]=useState("");return <div className="card"><h3 className="font-semibold mb-3">Goals</h3><div className="flex gap-2"><input className="input" placeholder="New goal" value={title} onChange={e=>setTitle(e.target.value)}/><button className="btn" onClick={()=>title&&setState((s:any)=>({...s,goals:[{id:uid(),title,description:"",category:"Personal",targetDate:"",progress:0,status:"Not started",milestones:[]},...s.goals]}))}>Add</button></div><div className="mt-3 space-y-2">{state.goals.map((g:Goal)=><div key={g.id} className="rounded-xl bg-slate-800 p-3"><p>{g.title}</p><input type="range" min={0} max={100} value={g.progress} onChange={e=>setState((s:any)=>({...s,goals:s.goals.map((x:Goal)=>x.id===g.id?{...x,progress:+e.target.value}:x)}))}/><button className="btn mt-2" onClick={()=>grantXp(25)}>Milestone complete (+25 XP)</button></div>)}</div></div>}
function Study({state,setState,grantXp}:any){const [mins,setMins]=useState(30);const [skill,setSkill]=useState("Cybersecurity");return <div className="card"><h3 className="font-semibold">Study Tracker</h3><div className="flex gap-2 my-3"><select className="input" value={skill} onChange={e=>setSkill(e.target.value)}>{state.skills.map((s:Skill)=><option key={s.name}>{s.name}</option>)}</select><input className="input" type="number" value={mins} onChange={e=>setMins(+e.target.value)}/><button className="btn" onClick={()=>{setState((s:any)=>({...s,skills:s.skills.map((x:Skill)=>x.name===skill?{...x,xp:x.xp+mins}:x)}));grantXp(mins);}}>Log study</button></div>{state.skills.map((s:Skill)=><div key={s.name} className="mb-2"><div className="flex justify-between text-sm"><span>{s.name}</span><span>Lvl {lvl(s.xp)} ({s.xp} XP)</span></div><div className="h-2 bg-slate-800 rounded"><div className="h-2 bg-emerald-500 rounded" style={{width:`${(s.xp/xpToNext(s.xp))*100}%`}}/></div></div>)}</div>}
function Fitness({state,setState,totals}:any){const [m,setM]=useState({name:"",calories:0,protein:0,carbs:0,fat:0});return <div className="card"><h3 className="font-semibold">Fitness & Macros</h3><div className="grid grid-cols-5 gap-2 my-2"><input className="input" placeholder="Meal" value={m.name} onChange={e=>setM({...m,name:e.target.value})}/>{["calories","protein","carbs","fat"].map((k)=><input key={k} className="input" type="number" placeholder={k} onChange={e=>setM({...m,[k]:+e.target.value})}/>)}</div><button className="btn" onClick={()=>setState((s:any)=>({...s,meals:[{id:uid(),...m},...s.meals]}))}>Add meal</button><p className="mt-3">Calories: {totals.consumed.cal}/{state.settings.calories}</p></div>}
function Money({state,setState,totals}:any){const [e,setE]=useState({type:"expense",amount:0,category:"General"});return <div className="card"><h3 className="font-semibold">Money Goals</h3><div className="grid grid-cols-3 gap-2 my-2"><select className="input" onChange={x=>setE({...e,type:x.target.value})}><option>income</option><option>expense</option><option>savings</option><option>debt</option></select><input className="input" type="number" onChange={x=>setE({...e,amount:+x.target.value})}/><input className="input" placeholder="Category" onChange={x=>setE({...e,category:x.target.value})}/></div><button className="btn" onClick={()=>setState((s:any)=>({...s,entries:[{id:uid(),...e},...s.entries]}))}>Add entry</button><p className="mt-3">Spent ${totals.spent} • Saved ${totals.saved}</p></div>}
function Notes({state,setState}:any){const [n,setN]=useState({title:"",body:"",tags:""});const [q,setQ]=useState(""); const filtered=state.notes.filter((x:Note)=>`${x.title} ${x.tags}`.toLowerCase().includes(q.toLowerCase()));return <div className="card"><h3 className="font-semibold">Notes</h3><input className="input my-2" placeholder="Search" value={q} onChange={e=>setQ(e.target.value)}/><div className="grid gap-2 md:grid-cols-3"><input className="input" placeholder="Title" onChange={e=>setN({...n,title:e.target.value})}/><input className="input" placeholder="Tags" onChange={e=>setN({...n,tags:e.target.value})}/><button className="btn" onClick={()=>setState((s:any)=>({...s,notes:[{id:uid(),pinned:false,...n},...s.notes]}))}>Add note</button></div>{filtered.map((x:Note)=><div key={x.id} className="rounded-xl bg-slate-800 p-3 mt-2"><p>{x.title}</p><p className="text-sm text-slate-400">{x.tags}</p><button className="btn mt-2" onClick={()=>setState((s:any)=>({...s,notes:s.notes.filter((n:Note)=>n.id!==x.id)}))}>Delete</button></div>)}</div>}
function Review({state,setState,grantXp}:any){const [r,setR]=useState({done:"",slowed:"",learned:"",focus:"",rating:7});return <div className="card"><h3 className="font-semibold">Daily Review</h3>{Object.keys(r).map(k=><input key={k} className="input my-1" placeholder={k} onChange={e=>setR({...r,[k]:k==='rating'?+e.target.value:e.target.value})}/>) }<button className="btn mt-2" onClick={()=>{setState((s:any)=>({...s,reviews:[{id:uid(),...r},...s.reviews]}));grantXp(30);}}>Save Review (+30 XP)</button></div>}
function Settings({state,setState}:any){const s=state.settings;return <div className="card"><h3 className="font-semibold">Settings</h3><div className="grid md:grid-cols-2 gap-2 mt-2">{Object.entries(s).map(([k,v]:any)=><input key={k} className="input" value={String(v)} placeholder={k} onChange={e=>setState((st:any)=>({...st,settings:{...st.settings,[k]:e.target.value}}))}/>)}</div></div>}
function Assistant(){const prompts=["Plan my day","Review my goals","Create a study plan","Improve this sales message","Summarize my progress","What should I focus on today?"]; const [msgs,setMsgs]=useState([{role:"assistant",text:"I’m your Life OS assistant. Ask me for guidance."}]); const [i,setI]=useState(""); const send=(t:string)=>{if(!t)return; setMsgs(m=>[...m,{role:"user",text:t},{role:"assistant",text:`Mock: Based on Life OS data, prioritize one high-impact task, one study session, and one recovery habit.`}]); setI("");}; return <aside className="card h-fit"><h3 className="font-semibold mb-2">Assistant</h3><div className="space-y-2 max-h-80 overflow-auto">{msgs.map((m,idx)=><div key={idx} className={`text-sm p-2 rounded-xl ${m.role==='assistant'?'bg-slate-800':'bg-indigo-600/40'}`}>{m.text}</div>)}</div><div className="flex flex-wrap gap-1 my-2">{prompts.map(p=><button key={p} className="btn text-xs" onClick={()=>send(p)}>{p}</button>)}</div><div className="flex gap-2"><input className="input" value={i} onChange={e=>setI(e.target.value)} placeholder="Ask assistant..."/><button className="btn" onClick={()=>send(i)}>Send</button></div></aside>}
